travis:
  secure:
    BINSTAR_TOKEN: fXRSgKh3xQbkUQkBiLMwLDZIxq8zocXAGgfehhVycKqookrdZ7tTH78QJqzg155i0QKWK3qA4EdYnEtjMfwjSW4ABZiRheCqWA2y5+NAM2m+NN9Vl14voq/lR6uNA7s8A0e0/jIH7jMg0UNns/IvA/b6Ag7SMnnPjz6TmkATFT/HotYs8mxp3mbZmJsXAlOpYSqypWBPYz+xvW128oul3JFuEYLFJZ6A/cMtB5dxTvTP0rN8u2w6u2kDEkeGc/qKJ8W8EIcr7A+lSd1oEGAFzEyxpb/yINplYbn5XvC2Z2r+W70mb+3Zm5CXr5wuuHsCH2AVzVqWMSIihuBVgPznD9/Yw4XtKSS6xKZ0cljMmiZQBI+rNtg3O18k56bJky56OROeD/mxUfT54us84VYxNzzJvj/X3KD409I9CzZkzGjdEx+TG3PkCnvs7msENt0/9EFWdjuB9lJyLrB+ZNo7JetH70duqj0xCdEfcEtXIcqnrSSglaFdwDqy94aRnB6bZJ2oODIGtVbswVS6PbP5TF2O0Q9qEqliQW1yu/IKy+Z8ksILf6uyAeuTlKt2eOFhwlRb36LFnaHPtLJ/HVS6u2eFQer7J+tRxcSSlA6+WmuKenkFby5TWMG/XWroy6iHwbelYe+Ga02k3jyQBmyA0PaRWtkQ35ysXSbDoP7HelA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
