travis:
  secure:
    BINSTAR_TOKEN: V0boRy6hTkzZiWSn022Ds+9nWANXax17PVYm6y7N9iJmdbspjaKGjDjxRWZ6PpVXkeP9cdHI5C+rcK/Fe1Jj1yxRPnZX5EwyCh7bx0TMdTp5HZbzy2uLbLzRWtbgyPR1TUhsDEX1KlK+ZheYiU6BWlEOu3TWpXU4ks+UQ8VRWWbcaSQqb2R11rP5SplmilvWp6pYlnyG2kP8lZsACvVPl24sH+rvPm3rlGWteAMrczzbX4E1cGVktjH3qu0rXxLpx0WL4p87dgF+HSWh6Opx+iHO86ExiJetOVAmLchY0f2K5+lOOT4OSqtCex7zq6rot2r+UEV5LzJwXNxbej9wt88SWn+VyeKOoehMmqrH+rbjhxG5TmClWR8OO7vl1TF5hD7xW2rXRN+eb/3r7oBTboI9tl4ACVBnlVMVsdaP6N6m0rHmj4eZmdIfgWs/9pdcm7RepyY90F6vC9Nx1uTrx8748wHnMPYmewMWQlycTtb69vQU5kOamGBFpgFokMogTL/Qed9lR6G6FE0ZPQinWoPv5hjxrVUIe63fEACgiNWn1lQye0XZsFqyju86IJmF6aJxje0z6DjOfssFw2TxUdReYTIBtipb9pOajGQls9k/lBxYAqkQ6LaAgWSm7ZVNl8cmT07FlZUaNWx+4HEVhVkBC7RtQFJlg4GGwYtEpMw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
