travis:
  secure:
    BINSTAR_TOKEN: r/LOpJ0u/it85uft6E1jRtkEr3emsjXaEu+VYyXCTHp9q8UuGZih6gKV8HtUmc/Jf4Vy1PuWcJkfWDlxIPXwhxlmig9Ri1C7/1g3rUIFCMZjVe/FOOOOadS9tBFsrQ+BYyKhsH+7ohqClry8/A8gdXq+/+VKrkB6YyVW4J8KLYAWZk3uwJoEy4MArO3DPK9ynhyfrcTS3in6L0+733JFaY9kGAJeBlTU6OqLXbXfACCtWi1EcYlvPjemVtKmOqSzjF5BtAFJ1uQGA0EJ72IRCbItX8pDDYadXAE4nTWyv3311fapiDOD8S/bNAstowP9n9VAqMOdS3JJxjOH9idi1ELQAEiPICmALRuh+lKYP0JFNCMnFgYLulMH/a68BINyGVKbjv0oefIPBRnFl/rOBIpsI8kwklh2H95a+qeLMAl4k+9smOcid68zb1ofOftvxcaRMSsjMTB8DvLHKrOPbuasCvdGsOWJvaUw+frd8ZwdaBp+lUmunmltsQ2wbORyqSovVp67zOF8ZN0otqt9qcWsnNi+9Pmpsir014aKJyn1zqZue/cN7M2tZZdVFJ/bjbDwJDAIVXPG2n7XAXNsuXV4AlQCd/vvO5KJ4EtMP7GObmCVZdypNmev+BRTpIp+2r/SPYxQ10yv4a/YUdnR6VPsIRu4+ODy77MOXgcbNzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
