travis:
  secure:
    BINSTAR_TOKEN: RVIRzyxWd0D/vt3nO/2DrWA1NGliogAC+jdMgVuO4tFeOP3GQEGlDAHCsO+OEbNQ24OM5xJXCays5K9rXkX/z2MI647C/vAzobFKx2o5VEM+wYr4N+xhkZD0Du47BU/E2/9UjNjxV2xKvHLgi5gFTCJ9xq4Z9L0YxpmvIKaYS0ByBmjXQaBVt3IOsLB/VNPiFOwEdN7vT4TT6rESuJ+pz+r1zvfCmOJu0sKRCbGsYkug8f82w6pHNGrDjJ7FiOH6H969Xswegc6NoUXZiobuK2T7ybJgyCcamEljX4YRhxWljCPmhNF1RxHZk/DLUtgYD3WRw7MCMMg/2XdtPBfmIzdtyZWwrjpNzXhGiGcHTLrE/KjW+Ir7sB4qV1uTqoA3XuZl+UFMDOAkbKyTZCYmKVXZVXcnzMTgMcwiywx715U2AiV3Q9BLQ8r5oAmn7ctjVxEgAwzagGlFAVKjVPX8RjVVUsJ0iBNqv241ypWL0//+OcC0ebCpAtiQbt/X4QbEmfUVT3p/p4IrQsF1IEURTw8ZEn0KYs5WqMbeFur0+m5Lj4eFV5zEYbshvq1eSW7N63CySUdXMFTc2DYfFzDJ+rsRahof7oDitUnAXVqw3iw2BmbT+gYsnCrbRm6ptJY4bBTJ21HXLQryVAsh7k2P2X3/cqSZn0IfJAFOYz9SioE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
